
import java.awt.Font;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author PC
 */
public class Przelaczniki extends javax.swing.JFrame {

    /**
     * Creates new form Przelaczniki
     */
    public Przelaczniki() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupSize = new javax.swing.ButtonGroup();
        malyPrzelacznik = new javax.swing.JRadioButton();
        sredniPrzelacznik = new javax.swing.JRadioButton();
        duzyPrzelacznik = new javax.swing.JRadioButton();
        tLabel = new javax.swing.JLabel();

        groupSize.add(malyPrzelacznik);
        groupSize.add(sredniPrzelacznik);
        groupSize.add(duzyPrzelacznik);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        malyPrzelacznik.setText("Mały");
        malyPrzelacznik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                malyPrzelacznikActionPerformed(evt);
            }
        });

        sredniPrzelacznik.setText("Średni");
        sredniPrzelacznik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sredniPrzelacznikActionPerformed(evt);
            }
        });

        duzyPrzelacznik.setText("Duży");
        duzyPrzelacznik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duzyPrzelacznikActionPerformed(evt);
            }
        });

        tLabel.setText("Coś");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(malyPrzelacznik)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sredniPrzelacznik)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(duzyPrzelacznik))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tLabel)
                        .addGap(84, 84, 84)))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {duzyPrzelacznik, malyPrzelacznik, sredniPrzelacznik});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(malyPrzelacznik)
                    .addComponent(sredniPrzelacznik)
                    .addComponent(duzyPrzelacznik))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(tLabel)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void malyPrzelacznikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_malyPrzelacznikActionPerformed
        tLabel.setFont(new Font("Monospace", Font.ITALIC, 15));
    }//GEN-LAST:event_malyPrzelacznikActionPerformed

    private void sredniPrzelacznikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sredniPrzelacznikActionPerformed
        tLabel.setFont(new Font("Monospace", Font.ITALIC, 25));
    }//GEN-LAST:event_sredniPrzelacznikActionPerformed

    private void duzyPrzelacznikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duzyPrzelacznikActionPerformed
        tLabel.setFont(new Font("Monospace", Font.ITALIC, 35));
    }//GEN-LAST:event_duzyPrzelacznikActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Przelaczniki.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Przelaczniki.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Przelaczniki.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Przelaczniki.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Przelaczniki().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton duzyPrzelacznik;
    private javax.swing.ButtonGroup groupSize;
    private javax.swing.JRadioButton malyPrzelacznik;
    private javax.swing.JRadioButton sredniPrzelacznik;
    private javax.swing.JLabel tLabel;
    // End of variables declaration//GEN-END:variables
}
